### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by ColinEberhardt** [WPFerg/d3fc-sample#2]
Nice Job :-)

Here's a few bits of feedback ...

Be more functional!!!

    var bucket = function(data) {
        var numberOfBuckets = Math.ceil(data.length / bucketSize);

        return d3.range(0, numberOfBuckets).map((i) => {
            return data.slice(i * bucketSize, (i + 1) * bucketSize);
        });
    };

Can be simplified to: 

    var bucket = function(data) {
        return d3.range(0, Math.ceil(data.length / bucketSize)).map((i) => {
            return data.slice(i * bucketSize, (i + 1) * bucketSize);
        });
    };

Which allows you to drop the braces:

    var bucket = d3.range(0, Math.ceil(data.length / bucketSize)).map((i) => {
            return data.slice(i * bucketSize, (i + 1) * bucketSize);
        });

Or even just:

    const bucket = d3.range(0, Math.ceil(data.length / bucketSize))
                            .map((i) => data.slice(i * bucketSize, (i + 1) * bucketSize));

**Comment by ColinEberhardt** [comment]
I'd get rid of `identity.js`, the expanded form: `(d) => d` is more concise and easier to understand.

**Comment by WPFerg** [comment]
@ColinEberhardt Thanks, I hadn't spotted that `bucket.js` could do with that tidy up after the ongoing refactor to try and make everything more functional. I'll see if there's any more places where something similar could be applied.

I wasn't too sure about `identity`, just because it's a shared utility function, but it's concise enough to not be too bad if it's repeated, so I'll remove that too.

**Comment by WPFerg** [comment]
I've done these, and an additional refactor on largestTriangleThree, but will leave open for additional feedback

**Comment by ColinEberhardt** [comment]
:+1: looks good to me

**Comment by WPFerg** [comment]
@ColinEberhardt Do you want me to squash and transfer ownership?
